const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const ffmpeg = require('fluent-ffmpeg');
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;

ffmpeg.setFfmpegPath(ffmpegPath);

/**
 * Process audio file to remove speech/vocals
 * Supports both Python-based (Demucs) and fallback methods
 */
async function processAudio(inputPath, outputPath, progressCallback) {
  const tempDir = path.join(require('os').tmpdir(), 'gettunes_' + Date.now());

  try {
    // Create temp directory
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    progressCallback({ percent: 10, message: 'Initialisierung...' });

    // Try Demucs first (works with Python 3.8-3.14)
    try {
      progressCallback({ percent: 20, message: 'Trenne Sprache von Musik mit Demucs AI...' });
      await runDemucs(inputPath, tempDir, progressCallback);

      const instrumentalPath = findInstrumentalFile(tempDir, inputPath);
      await convertToMp3(instrumentalPath, outputPath);

      progressCallback({ percent: 100, message: 'Fertig!' });
      return;
    } catch (demucsError) {
      console.error('Demucs failed, trying fallback method:', demucsError.message);
      progressCallback({ percent: 30, message: 'Verwende alternative Methode...' });

      // Fallback: Use spectral subtraction method
      await processWithSpectralMethod(inputPath, outputPath, progressCallback);
    }

  } catch (error) {
    throw new Error(`Verarbeitungsfehler: ${error.message}`);
  } finally {
    // Cleanup temp directory
    if (fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }
}

/**
 * Run Demucs vocal separation (supports Python 3.14+)
 */
function runDemucs(inputPath, outputDir, progressCallback) {
  return new Promise((resolve, reject) => {
    // Try to find Python
    const pythonCandidates = ['python', 'python3', 'py'];
    let pythonCmd = null;

    // Test which Python command works
    for (const cmd of pythonCandidates) {
      try {
        const test = require('child_process').spawnSync(cmd, ['--version']);
        if (test.status === 0) {
          pythonCmd = cmd;
          break;
        }
      } catch (e) {
        continue;
      }
    }

    if (!pythonCmd) {
      return reject(new Error('Python nicht gefunden. Bitte installiere Python 3.8+ oder verwende die Fallback-Methode.'));
    }

    // Use demucs via Python module
    const demucsArgs = [
      '-m', 'demucs',
      '--two-stems=vocals',
      '-o', outputDir,
      '--mp3',
      '--mp3-bitrate', '320',
      inputPath
    ];

    const demucsProcess = spawn(pythonCmd, demucsArgs);
    let errorOutput = '';

    demucsProcess.stderr.on('data', (data) => {
      const output = data.toString();
      errorOutput += output;

      // Parse progress from Demucs output
      const progressMatch = output.match(/(\d+)%/);
      if (progressMatch) {
        const percent = 20 + (parseInt(progressMatch[1]) * 0.6);
        progressCallback({ percent, message: 'Trenne Sprache von Musik...' });
      }
    });

    demucsProcess.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Demucs konnte nicht ausgeführt werden (Code ${code}). Verwende Fallback-Methode.`));
      }
    });

    demucsProcess.on('error', (err) => {
      reject(new Error('Demucs nicht verfügbar. Verwende Fallback-Methode.'));
    });
  });
}

/**
 * Find the instrumental file generated by Demucs
 */
function findInstrumentalFile(tempDir, originalPath) {
  const originalName = path.basename(originalPath, path.extname(originalPath));

  const searchDirs = [
    path.join(tempDir, 'htdemucs', originalName),
    path.join(tempDir, 'mdx_extra', originalName),
    path.join(tempDir, 'mdx', originalName),
    path.join(tempDir, 'htdemucs_ft', originalName),
  ];

  for (const dir of searchDirs) {
    if (fs.existsSync(dir)) {
      const noVocalsFile = path.join(dir, 'no_vocals.mp3');
      if (fs.existsSync(noVocalsFile)) {
        return noVocalsFile;
      }
    }
  }

  throw new Error('Instrumentale Datei nicht gefunden.');
}

/**
 * Fallback method: Spectral-based vocal reduction
 * This uses FFmpeg filters to reduce vocals when Demucs is not available
 */
function processWithSpectralMethod(inputPath, outputPath, progressCallback) {
  return new Promise((resolve, reject) => {
    progressCallback({ percent: 40, message: 'Verwende Spektral-Analyse für Vokalentfernung...' });

    // Use FFmpeg's vocal reduction filter (center channel isolation + removal)
    // This is a simpler method but still effective for many recordings
    ffmpeg(inputPath)
      .audioFilters([
        // Extract side channels (this removes center-panned vocals)
        'pan=stereo|c0<c0-c1|c1<c1-c0',
        // Apply high-pass and low-pass filters to isolate music
        'highpass=f=100',
        'lowpass=f=16000',
        // Normalize
        'loudnorm'
      ])
      .audioCodec('libmp3lame')
      .audioBitrate('320k')
      .on('progress', (progress) => {
        if (progress.percent) {
          const percent = 40 + (progress.percent * 0.5);
          progressCallback({ percent, message: 'Verarbeite Audio...' });
        }
      })
      .on('end', () => {
        progressCallback({ percent: 100, message: 'Fertig!' });
        resolve();
      })
      .on('error', (err) => {
        reject(new Error(`FFmpeg Fehler: ${err.message}`));
      })
      .save(outputPath);
  });
}

/**
 * Convert audio to MP3
 */
function convertToMp3(inputPath, outputPath) {
  return new Promise((resolve, reject) => {
    ffmpeg(inputPath)
      .audioCodec('libmp3lame')
      .audioBitrate('320k')
      .on('end', () => resolve())
      .on('error', (err) => reject(new Error(`FFmpeg Fehler: ${err.message}`)))
      .save(outputPath);
  });
}

module.exports = { processAudio };
