const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const ffmpeg = require('fluent-ffmpeg');
const ffmpegPath = require('@ffmpeg-installer/ffmpeg').path;

ffmpeg.setFfmpegPath(ffmpegPath);

/**
 * Process audio file to remove speech/vocals
 * Uses Demucs for high-quality vocal separation
 */
async function processAudio(inputPath, outputPath, progressCallback) {
  const tempDir = path.join(require('os').tmpdir(), 'gettunes_' + Date.now());

  try {
    // Create temp directory
    if (!fs.existsSync(tempDir)) {
      fs.mkdirSync(tempDir, { recursive: true });
    }

    progressCallback({ percent: 10, message: 'Initialisierung...' });

    // Step 1: Run Demucs separation
    progressCallback({ percent: 20, message: 'Trenne Sprache von Musik (dies kann einige Minuten dauern)...' });
    await runDemucs(inputPath, tempDir, progressCallback);

    // Step 2: Find the instrumental output from Demucs
    progressCallback({ percent: 80, message: 'Finalisiere Audio...' });
    const instrumentalPath = findInstrumentalFile(tempDir, inputPath);

    // Step 3: Copy/convert to output path
    await convertToMp3(instrumentalPath, outputPath);

    progressCallback({ percent: 100, message: 'Fertig!' });

  } catch (error) {
    throw new Error(`Verarbeitungsfehler: ${error.message}`);
  } finally {
    // Cleanup temp directory
    if (fs.existsSync(tempDir)) {
      fs.rmSync(tempDir, { recursive: true, force: true });
    }
  }
}

/**
 * Run Demucs vocal separation
 */
function runDemucs(inputPath, outputDir, progressCallback) {
  return new Promise((resolve, reject) => {
    // Check if Python is available
    const pythonCmd = process.platform === 'win32' ? 'python' : 'python3';

    // Use demucs via Python
    // Note: Requires Demucs to be installed: pip install demucs
    const demucsArgs = [
      '-m', 'demucs',
      '--two-stems=vocals',  // Only separate vocals vs rest
      '-o', outputDir,
      '--mp3',               // Output as MP3
      '--mp3-bitrate', '320', // High quality
      inputPath
    ];

    const demucsProcess = spawn(pythonCmd, demucsArgs);

    let errorOutput = '';

    demucsProcess.stderr.on('data', (data) => {
      const output = data.toString();
      errorOutput += output;

      // Try to parse progress from Demucs output
      const progressMatch = output.match(/(\d+)%/);
      if (progressMatch) {
        const percent = 20 + (parseInt(progressMatch[1]) * 0.6); // Scale to 20-80%
        progressCallback({ percent, message: 'Trenne Sprache von Musik...' });
      }
    });

    demucsProcess.on('close', (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Demucs Fehler (Code ${code}): ${errorOutput || 'Unbekannter Fehler'}`));
      }
    });

    demucsProcess.on('error', (err) => {
      if (err.code === 'ENOENT') {
        reject(new Error('Python oder Demucs nicht gefunden. Bitte installiere Python 3.8-3.11 und Demucs (pip install demucs).'));
      } else {
        reject(err);
      }
    });
  });
}

/**
 * Find the instrumental file generated by Demucs
 */
function findInstrumentalFile(tempDir, originalPath) {
  const originalName = path.basename(originalPath, path.extname(originalPath));

  // Demucs output structure: tempDir/htdemucs/originalName/no_vocals.mp3
  const searchDirs = [
    path.join(tempDir, 'htdemucs', originalName),
    path.join(tempDir, 'mdx_extra', originalName),
    path.join(tempDir, 'mdx', originalName),
  ];

  for (const dir of searchDirs) {
    if (fs.existsSync(dir)) {
      const noVocalsFile = path.join(dir, 'no_vocals.mp3');
      if (fs.existsSync(noVocalsFile)) {
        return noVocalsFile;
      }
    }
  }

  throw new Error('Instrumentale Datei nicht gefunden. Demucs-Verarbeitung möglicherweise fehlgeschlagen.');
}

/**
 * Convert audio to MP3 if needed
 */
function convertToMp3(inputPath, outputPath) {
  return new Promise((resolve, reject) => {
    ffmpeg(inputPath)
      .audioCodec('libmp3lame')
      .audioBitrate('320k')
      .on('end', () => resolve())
      .on('error', (err) => reject(new Error(`FFmpeg Fehler: ${err.message}`)))
      .save(outputPath);
  });
}

module.exports = { processAudio };
